softeerbootcamp/Team6-Oil-Pocket

- backend/build.gradle
- backend/src/main/java/com/kaspi/backend/BackendApplication.java
- backend/src/main/java/com/kaspi/backend/domain/GasDetail.java
- backend/src/main/java/com/kaspi/backend/domain/GasStation.java
- backend/src/main/java/com/kaspi/backend/enums/GasType.java
- backend/src/main/java/com/kaspi/backend/util/DataDownloadScheduler.java
- backend/src/test/java/com/kaspi/backend/domain/GasDetailTest.java
- backend/src/test/java/com/kaspi/backend/util/DataDownloadSchedulerTest.java
Issue Number: #3 
- 셀레니움을 통해서 오피넷에 접속합니다
- 주유소와 가스충전소 다운로드 버튼 클릭 이벤트가 발생합니다
- 해당 리스트를 다운로드 받고 ("/Users/download") 경로에 저장 됩니다 --> 맥북 개발 환경
- 현재는 확인용으로 해당작업이 끝나는 기준으로 2초 주기로 스케줄러가 작동합니다 -> 스프링부트 실행시 주기를 변경시키거나 주석처리를 해서 실행에 함께되지 않도록 주의해주세요.
- 맥북과 운영서버 환경(OS)가 달라서 다운로드 경로를 배포시 변경 시켜야 합니다 --> 추후 고려할 예정
- 꼭 스케줄러 주기를 주의해주세요
> Feature/3 gas station data download -> dev : 주유소와 가스충전소의 리스트를 다운로드 받는 기능 구현

- .gitignore
- backend/build.gradle
- backend/src/main/resources/application.yml
- backend/src/test/java/com/kaspi/backend/RedisConnectionTest.java
- backend/src/test/resources/application.yml
Issue Number: #18 
- redis ec2에 docker로 구동
- springboot에서 redis 연동을 위한 yml, dependency 수정
- redis 연동 테스트
- test db로 yml파일 추가(h2db)
- springboot 2.0이상 부터 RedisTemplate Config를 만들지 않고 바로 사용가능합니다.
> Feature/redis conf->dev: redis SpringBoot 연동

- backend/src/main/java/com/kaspi/backend/util/config/WebConfig.java
> feature/#40_cors_setting->dev: cors에러 수정

- backend/src/main/java/com/kaspi/backend/util/config/WebConfig.java
-allowCredentials 설정 true로 변경
- Cookie값을 가져오기 위한 설정 변경
> dev->main:cors에러 및 쿠키 설정을 위한 allowCredentials값 true 설정

- backend/src/main/java/com/kaspi/backend/util/config/WebConfig.java
- backend/src/main/java/com/kaspi/backend/util/filter/FilterConfig.java
> [hotfix]local:dev->dev: origins cors 프론트 로컬로 변경

- backend/src/main/java/com/kaspi/backend/util/config/WebConfig.java
- #53참고
- corsorigin-credential false 설정
> [HotFix] dev->main: cors 에러 수정

- backend/src/main/java/com/kaspi/backend/util/config/WebConfig.java
- #53 
- cors origin localhost에서 127.0.0.1로 변경
> [Hotfix] dev->main: 프론트 cors localhost에서 127.0.0.1로 변경

- backend/src/main/java/com/kaspi/backend/util/cookie/CookieSerialize.java
- cookie same-site 옵션 변경 none으로
> [Hotfix] local dev-> dev

- backend/src/main/java/com/kaspi/backend/util/config/WebConfig.java
- samesite option 변경 none으로
- #57 
제발 돼라....
> [Hotfix] dev-> main :samesite option 변경 

- backend/src/main/java/com/kaspi/backend/util/DataDownloadScheduler.java
테스트 배포를 위해 리눅스 파일 경로로 변경하고 스케쥴러 시간을 12시 10분으로 변경함
Issue Number:
> #4 hotfix: 리눅스 서버 파일 구조 경로 반영

- backend/src/main/java/com/kaspi/backend/service/GasDataService.java
- backend/src/main/java/com/kaspi/backend/util/DataDownloadScheduler.java
> [Hotfix] dev-> dev : 빈 주입 버그 수정

- backend/src/main/java/com/kaspi/backend/service/GasDataService.java
- backend/src/main/java/com/kaspi/backend/util/DataDownloadScheduler.java
> [Hotfix] dev-> main : #4 빈 주입 버그 수정

- backend/src/main/java/com/kaspi/backend/domain/GasDetail.java
- backend/src/main/java/com/kaspi/backend/domain/GasStation.java
- backend/src/main/java/com/kaspi/backend/util/DataDownloadScheduler.java
> [Hotfix] dev-> main : #4 빈 못찾는 배포 오류 수정

- backend/src/main/java/com/kaspi/backend/domain/GasStation.java
- backend/src/main/java/com/kaspi/backend/util/DataDownloadScheduler.java
- GasStation 빈을 못찾는 버그 수정
-  @Table 어노테이션을 통해 엔티티와 테이블 매핑
- 스케쥴러 시간 변경
> [Hotfix] dev-> dev : #4 엔티티 db 매핑 수정

- backend/src/main/java/com/kaspi/backend/domain/GasStationDto.java
> [Hotfix] dev-> dev : #4 GasStationDto 변경 반영

- backend/src/main/java/com/kaspi/backend/util/DataDownloadScheduler.java
> [Hotfix] dev-> dev : #4 hotfix: 스케쥴러 시간 설정 오류 수정

- backend/src/main/java/com/kaspi/backend/domain/GasStationDto.java
- backend/src/main/java/com/kaspi/backend/util/DataDownloadScheduler.java
> [Hotfix] dev-> main : #4 hotfix: 스케쥴러 시간 설정 오류 수정

- backend/src/main/java/com/kaspi/backend/util/DataDownloadScheduler.java
> [Hotfix] dev-> dev : #4 hotfix: 크롬드라이버 설치 경로 설정 수정

- backend/src/main/java/com/kaspi/backend/util/DataDownloadScheduler.java
> [Hotfix] dev-> main : #4 hotfix: 크롬드라이버 설치 경로 설정 수정

- backend/src/main/java/com/kaspi/backend/util/DataDownloadScheduler.java
> [Hotfix] dev-> dev : #4 hotfix: 서버 디스플레이 설정 추가

- backend/src/main/java/com/kaspi/backend/util/DataDownloadScheduler.java
> [Hotfix] dev-> main : #4 hotfix: 서버 디스플레이 설정 추가

- backend/src/main/java/com/kaspi/backend/util/DataDownloadScheduler.java
> [Hotfix] dev-> dev : #4 hotfix: chromedriver 경로 변경

- backend/src/main/java/com/kaspi/backend/util/DataDownloadScheduler.java
> Dev[Hotfix] dev-> main: #4 chromedriver 경로 변경

- backend/src/main/java/com/kaspi/backend/util/DataDownloadScheduler.java
> [Hotfix] dev-> dev : #4  chrome option 수정

- backend/src/main/java/com/kaspi/backend/util/DataDownloadScheduler.java
> [Hotfix] dev-> main : #4 chrome option 수정

- backend/src/main/java/com/kaspi/backend/util/DataDownloadScheduler.java
> #4 hotfix: chromedriver 경로 변경

- backend/src/main/java/com/kaspi/backend/util/DataDownloadScheduler.java
> #4 hotfix: 경로 재설정

- backend/Dockerfile
- backend/src/main/java/com/kaspi/backend/util/DataDownloadScheduler.java
> [Hotfix] dev-> dev : #90 Dockerfile 수정

- backend/Dockerfile
- backend/src/main/java/com/kaspi/backend/util/DataDownloadScheduler.java
> [Hotfix] dev-> main : #90 도커 파일 수정

- backend/Dockerfile
> [Hotfix] dev-> dev : #90 hotfix(Dockerfile): 명령어 수정

- backend/Dockerfile
- backend/src/main/java/com/kaspi/backend/util/DataDownloadScheduler.java
> [Hotfix] dev-> main :  #90 hotfix(Dockerfile): 명령어 수정

- backend/src/main/java/com/kaspi/backend/domain/GasStationDto.java
<br>
<br>
- 주유소 한달 상세 정보에 원하시던 stationNo를 넣어드렸습니다~
<br>
<br>
<br>
> feature/149-gasStationDto-add-StationNo(GasStationDto) -> dev: stationNo 멤버변수 추가

- util/build.gradle
- util/src/main/java/org/example/Main.java
- util/src/main/java/org/example/scheduler/DataDownloadScheduler.java
<br>
<br>
- 기존 redis 의존성이 필요했던 버그를 수정하였습니다.
<br>
- Main 클래스에 @EnableScheduling 추가한 것만 아시면 됩니당~
<br>
- 웹훅으로 util 오류시 에러메시지 전송
<br>
> feature/147 find util redis bug -> dev : 

- util/build.gradle
- util/src/main/java/org/example/controller/ErrorController.java
- util/src/main/java/org/example/scheduler/DataDownloadScheduler.java
<br>
<br>
- 스케쥴러 일일 유가 다운로드 시작/종료 슬랙 알림 구현
- 스케쥴러 예외 발생시 printStackTrace() 메시지 슬랙 알림 구현
<br>
- slack api 사용법에 대해 주목해주세요
- 비즈니스 로직에도 slack api를 도입할지 생각해보아요.
<br>
- 스케쥴러 유가 다운로드시 서버타임존 버그 수정
<br>
> feature/152 slack noti -> dev: 스케쥴러 슬랙 알림 모니터링 기능 추가

- frontEnd/public/js/login/fetch.js
<br>
<br>
- 일부 라우팅 예외처리 해주었습니다. (로그인 여부 체크하지 않도록)
<br>
- 
<br>
- 마이페이지 통신
<br>
> hotfix:dev(router.js):라우팅 문제 해결

- frontEnd/public/js/login/fetch.js
<br>
<br>
- router.js를 원래 상태로 복구하였습니다.
<br>
- X
<br>
- router.js 작동 여부 확인
> hofix:dev(router.js):이전 상태로 복구

- frontEnd/public/js/common/function.js
- frontEnd/public/js/common/variable.js
- frontEnd/public/js/login/fetch.js
- frontEnd/public/js/myPage/comparison/fetch.js
- frontEnd/public/js/myPage/inputOilInfo/fetch.js
- frontEnd/public/js/register/fetch.js
<br>
<br>
- 배포 모드, 개발 모드 구분하도록 fetch 분기
<br>
- 깃 액션 작동 이후 요청이 올바르게 동작하는지 확인해주세요.
<br>
- 배포 UR에서 fetch가 올바르게 동작하는지 확인
> hotfix:dev(fetch):release, dev mode 구분하도록 설정

- frontEnd/public/js/router.js
<br>
<br>
- 로그인 체크 여부 임시 제외
<br>
- 배포된 사이트 확인
> hotfix:(frontEnd):로그인 체크 여부 임시 제외

- util/src/main/java/org/example/service/gasdata/GasDataService.java
<br>
<br>
- 스케쥴러가 작동할때 서버타임존이 달라서 이전 날짜로 삽입 되는 버그 수정
<br>
- 혹시 LocalDate.now() 메소드를 사용해서 db에 삽입하는 작업을 하실경우 서버타임존을 주의해주세요!
<br>
- csv 파일 정제 기능 추가
<br>
> feature/158 fix(GasDataService) -> dev: 서버타임존 수정

- frontEnd/public/js/login/fetch.js
- frontEnd/public/js/myPage/inputOilInfo/fetch.js
- frontEnd/public/js/router.js
<br>
<br>
- router 매번 로그인 체크 기능 추가
<br>
- hotfix 입니다.
<br>
- 배포 환경 확인
> hotfix:router 로그인 수정

- backend/build.gradle
- backend/src/main/java/com/kaspi/backend/controller/AuthController.java
- backend/src/main/java/com/kaspi/backend/controller/UserController.java
- backend/src/main/java/com/kaspi/backend/domain/User.java
- backend/src/main/java/com/kaspi/backend/dto/UserUpdateReqDto.java
- backend/src/main/java/com/kaspi/backend/service/AuthService.java
- backend/src/main/java/com/kaspi/backend/service/HttpSessionService.java
- backend/src/main/java/com/kaspi/backend/service/UserRecordService.java
- backend/src/main/java/com/kaspi/backend/service/UserService.java
- backend/src/main/java/com/kaspi/backend/util/encrypt/PasswordUtil.java
- backend/src/main/java/com/kaspi/backend/util/exception/ParameterException.java
- backend/src/main/java/com/kaspi/backend/util/response/code/DefaultCode.java
- backend/src/test/java/com/kaspi/backend/controller/AuthControllerTest.java
- backend/src/test/java/com/kaspi/backend/controller/UserControllerTest.java
- backend/src/test/java/com/kaspi/backend/dao/UserDaoTest.java
- backend/src/test/java/com/kaspi/backend/domain/UserTest.java
- backend/src/test/java/com/kaspi/backend/service/HttpSessionServiceTest.java
- backend/src/test/java/com/kaspi/backend/service/UserServiceTest.java
- backend/src/test/java/com/kaspi/backend/util/encrypt/PasswordUtilTest.java
<br>
<br>
- 로그아웃 API
- 회원수정 API
- 회원탈퇴 API
- 비밀번호 암호화하여 로그인 실행
<br>
- 회원탈퇴할때 SoftDelete를 굳이 해야할지 고민입니다. 만약 하게 된다면 UserTable에 flag를 확인하고 회원 수정, 삭제, 로그아웃, 로그인 등에서의 추가적인 로직이 필요합니다.
<br>
<br>
> Feature/#176 auth update-> dev:로그인/ 회원가입 추가 API

- frontEnd/public/js/common/variable.js
- frontEnd/public/js/myPage/userDetail/event.js
- frontEnd/public/js/myPage/userDetail/fetch.js
- frontEnd/public/js/myPage/userDetail/helperFunction.js
- frontEnd/public/js/myPage/userDetail/template.js
- frontEnd/public/js/myPage/userDetail/view.js
<br>
<br>
- 마이페이지 프로필 수정 통신 연결
<br>
- 템플릿 오타가 없는지 확인해주세요.
<br>
- 지도 뷰 스타일링
> Feature/190 마이페이지 프로필 수정 통신 연결 -> dev

- frontEnd/public/js/myPage/comparison/helperFunction.js
<br>
<br>
- 영어로 출력되던 성별을 한글로 매핑해주었습니다.
<br>
- 남자, 여자 모두 잘 출력되는지 확인해주세요.
<br>
- 마이페이지 이번 달 분석 로직 수정
> Feature/196 마이페이지 이번 달 분석 성별 매핑 -> dev

- frontEnd/public/js/myPage/history/template.js
- frontEnd/public/js/myPage/history/view.js
<br>
<br>
- 마이페이지 주유 기록 열람의 절약 금액 로직 수정
<br>
- 절약 금액이 양수일 때는 빨간색, 음수일 때는 파란색으로 출력되는지 확인해주세요.
<br>
- 지도 스타일링
<br>
> hotfix:주유 기록 열람 절약 금액 로직 수정 -> dev

- frontEnd/public/js/myPage/chart/fetch.js
<br>
<br>
- 마이페이지 차트 통신 예외 처리
<br>
- 빈 데이터에 관해서 통신이 잘 이루어지는 지 확인해주세요.
<br>
- 배포 환경 통신 확인
> hotfix:chartpage: 통신 예외 처리 추가 -> dev

- frontEnd/public/js/myPage/chart/fetch.js
- frontEnd/public/js/myPage/chart/helperFunction.js
<br>
<br>
- 차트 통신 예외처리를 추가하였습니다.
<br>
- 데이터가 없는 사용자에 한해서도 잘 작동되는지 검토해주세요.
<br>
- 배포 환경 차트 검토
> hotfix:마이페이지 통신 예외처리 -> dev

- frontEnd/public/js/common/variable.js
- frontEnd/public/js/login/fetch.js
- frontEnd/public/js/navbar/event.js
- frontEnd/public/js/navbar/view.js
<br>
<br>
- 로그아웃 통신 연결
- 로그아웃에 따른 뷰 변경
<br>
- 배포 환경에서도 로그아웃이 잘 되는지 확인해주세요.
<br>
- 김규민님과 협업 및 이후 작업 논의
> Feature/206 로그아웃 통신 연결 -> dev

- frontEnd/public/js/mapView/helperFunction.js
<br>
<br>
- 브랜드 이미지 경로를 수정하였습니다.
<br>
- S-Oil이 잘 출력되는지 검토해주세요.
<br>
- 배포 환경에서 S-Oil이 잘 나오는지 확인해주세요.
> hotfix:브랜드 이미지 경로 수정

- backend/src/main/java/com/kaspi/backend/controller/GasStationController.java
- backend/src/main/java/com/kaspi/backend/service/HttpSessionService.java
- backend/src/test/java/com/kaspi/backend/controller/GasStationControllerTest.java
- backend/src/test/java/com/kaspi/backend/service/HttpSessionServiceTest.java
<br>
<br>
- 주유소 상세페이지에서 로그인이 되어 있는경우에만 최근 주유소 저장 로직 수정
- 기존에는 세션이 자동적으로 생성되었는데 false옵션을 통해 생성 삭제
<br>
- 템플릿 오타가 없는지 확인해주세요.
<br>
- 노션 정리 및 개발 작업 문서화
<br>
> Feature/#185session error->dev: hotfix 최근 주유소 세션 저장 로직 변경

- frontEnd/public/js/mapView/event.js
- frontEnd/public/js/mapView/helperFunction.js
<br>
<br>
- mapView 변수 distanceOption 경로 수정
<br>
- Github Action이 올바르게 동작하는지 확인해주세요.
<br>
- Github Action check
> hotfix:mapview 변수 경로 수정

- frontEnd/public/js/login/template.js
<br>
<br>
- 로그인 계정을 미리 값으로 넣어두었습니다.
<br>
- 로그인이 정상적으로 이루어지는 지 확인해주세요.
<br>
- 마이페이지 차트 뷰 수정
> hotfix:로그인 계정 미리 넣어두기

- frontEnd/public/js/mapView/helperFunction.js
<br>
<br>
- 지도 상세텝 링크 텍스트에 "https"를 추가해주었습니다.
<br>
- 배포 환경에서도 https가 출력되는지 확인해주세요.
<br>
- 마이페이지 차트 스타일링 수정
> hotfix:mapView https 추가

- backend/src/main/java/com/kaspi/backend/service/UserRecordService.java
- backend/src/test/java/com/kaspi/backend/service/UserRecordServiceTest.java
<br>
<br>
- 절약 금액 음수 시 사진 범위 검색 버그 수정
<br>
- Math.abs() 함수를 이용해 절대값으로 사진의 범위를 가져오도록 수정하였습니다.
> hotfix dev -> dev: 절약 금액 음수 시 사진 범위 검색 버그 수정

- frontEnd/public/js/mapView/helperFunction.js
<br>
<br>
- 브랜드 이미지 경로 변경
<br>
- Ex oil 로고가 잘 나오는지 확인해주세요.
<br>
- 배포 환경 확인
> hotfix:이미지 경로 변경

- frontEnd/public/js/main/template.js
- frontEnd/public/js/myPage/chart/template.js
- frontEnd/public/js/myPage/comparison/template.js
- frontEnd/public/js/myPage/history/template.js
- frontEnd/public/js/myPage/inputOilInfo/template.js
- frontEnd/public/js/myPage/userDetail/template.js
<br>
<br>
- template.js의 불필요한 반복 코드를 제거하였습니다.
<br>
- 배포 환경에서 모든 뷰가 이전과 동일하게 출력되는지 확인해주세요.
<br>
- 배포 환경 체크
> Feature/232 template 반복 코드 수정 -> dev

- backend/src/main/java/com/kaspi/backend/controller/GasStationController.java
- backend/src/main/java/com/kaspi/backend/dao/GasStationDao.java
- backend/src/main/java/com/kaspi/backend/dto/FindGasStationResDto.java
- backend/src/main/java/com/kaspi/backend/service/GasStationService.java
- backend/src/main/java/com/kaspi/backend/service/HttpSessionService.java
- backend/src/test/java/com/kaspi/backend/controller/GasStationControllerTest.java
- backend/src/test/java/com/kaspi/backend/dao/GasStationDaoTest.java
- backend/src/test/java/com/kaspi/backend/service/GasStationServiceTest.java
- backend/src/test/java/com/kaspi/backend/service/HttpSessionServiceTest.java
<br>
<br>
- 주유기록 입력시 GasType도 입력받아 검색하도록 기능을 수정하였습니다.
- 최근주유소 리스트에서도 사용자가 입력한 유종을 취급하는 최근 주유소만 리스트로 출력하도록 수정하였습니다.
<br>
- RequestParam으로 GasType자체로 써도 받아지는거 처음 알았어요 ㅋㅋ...
<br>
<br>
> Feature/#221 gas search fix->dev: GasType을 받아 주유소 검색 및 최근주유소 리스트 출력

- frontEnd/public/js/login/fetch.js
- frontEnd/public/js/login/view.js
- frontEnd/public/js/register/view.js
<br>
<br>
- 로그인된 유저가 login, register 페이지에 진입할 경우 메인화면으로 이동하도록 설정
<br>
- 배포 환경에서 정상적으로 작동하는지 검토해주세요.
<br>
- 배포 환경 검토
> Feature/236 로그인되어있는경우 메인화면으로 라우팅 -> dev

- frontEnd/public/js/common/utils.js
- frontEnd/public/js/main/event.js
- frontEnd/public/js/main/helperFunction.js
- frontEnd/public/js/myPage/inputOilInfo/event.js
- frontEnd/public/js/myPage/inputOilInfo/fetch.js
<br>
<br>
- 헬퍼 함수 pipe를 모두 제거하였습니다.
<br>
- README 정리
> Feature/241 pipe 함수 불필요한 wrapper 제거 -> dev

- frontEnd/public/js/myPage/inputOilInfo/fetch.js
<br>
- [] 새로운 feature 추가
<br>
- 최근 열람 주유소 열람 로직 수정 (데이터가 비어 있어도 검색 기록을 초기화 할 수 있도록)
<br>
- 배포 환경에서 잘 열람되는지 확인해주세요.
<br>
- 배포 환경 검토
> hotfix:최근 주유소 열람 로직 수정

- backend/src/main/java/com/kaspi/backend/service/GasStationService.java
<br>
<br>
- 도로명주소 뒤 와일드카드 추가
<br>
- 빠른 배포를 위해 핫픽스
> hotfix(GasStationService) -> dev: address like 문에서 도로명 주소 뒤에도 와일드카드 추가

- frontEnd/public/js/myPage/inputOilInfo/event.js
- frontEnd/public/js/myPage/inputOilInfo/fetch.js
- frontEnd/public/js/myPage/inputOilInfo/view.js
<br>
<br>
- 최근 열람 주유소 버튼 이벤트 추가
<br>
- 배포 환경에서 잘 동작하는지 검토해주세요.
<br>
- 배포 환경 점검
> hotfix:최근 열람 주유소 통신 기능 추가

- backend/src/main/resources/static/index.html
- frontEnd/public/js/mapView/HelperFunction.js
- frontEnd/public/js/mapView/SearchFunction.js
- frontEnd/public/js/mapView/chart.js
- frontEnd/public/js/myPage/userDetail/event.js
<br>
<br>
- console.log 제거
<br>
- 배포 환경에서 콘솔 출력이 되는지 검토해주세요.
<br>
- 배포 환경 점검
> hotfix:console.log 제거

- frontEnd/public/js/notFound/view.js
<br>
<br>
- 404 페이지 템플릿 추가
<br>
- 배포 환경에서 404가 잘 출력되는지 확인해주세요.
<br>
- 배포 환경 점검
> hotfix:404페이지 내용 수정

- frontEnd/public/js/myPage/inputOilInfo/helperFunction.js
<br>
<br>
- 주유 입력 시 음수가 불가능하도록 설정
<br>
- 배포 환경을 점검해주세요.
<br>
- 배포 환경 점검
> hotfix:음수 입력 제한

- frontEnd/public/js/myPage/inputOilInfo/event.js
<br>
<br>
- 주유 입력 페이지 오류 수정
<br>
- 배포 환경 점검해주세요.
<br>
- 배포 환경 점검
> hotfix: 주유 입력 변경시 오류 수정

- backend/src/main/java/com/kaspi/backend/controller/UserGasRecordController.java
- backend/src/main/java/com/kaspi/backend/dto/UserGasRecordReqDto.java
- backend/src/main/java/com/kaspi/backend/service/UserRecordService.java
- backend/src/test/java/com/kaspi/backend/controller/UserGasRecordControllerTest.java
- backend/src/test/java/com/kaspi/backend/service/UserRecordServiceTest.java
<br>
<br>
- 절약금액 계산로직 수정
<br>
- 절약금액 계산시에 double로 변경하여 좀 더 정확한 계산과정을 하도록 재구성하였습니다.
<br>
<br>
> Feature/# code fix->dev: 절약금액 계산 로직 수정
